Update gen-ovpn
Refactored to use mail as the command that sends the email, and added dependency on a local MTA such as postfix setup as a relay to a mail server it is authorised to send mail to.

diff --git a/openvpn/Configs/gen-ovpn b/openvpn/Configs/gen-ovpn
--- a/openvpn/Configs/gen-ovpn
+++ b/openvpn/Configs/gen-ovpn
@@ -1,13 +1,11 @@
 #!/bin/bash
-# Pre-populate any constant variables here.
+# Pre-populate any constant variables here
 vpnname=""
 protocol=""
-relaydomain=""
+senderemail=""
 destinationemail=""
-authuser=""
-authpassword=""
 
-# Set the client anonymous client name. Can be overridden by specifying -v, but lowers anonimity.
+# Set the client anonymous client name. Can be overridden by specifying -v, but lowers anonimity
 name=client
 i=1
 if [[ -e /etc/openvpn/client-profiles/$name$i.ovpn ]] ; then
@@ -22,30 +20,27 @@ fi
 
 # Usage
 print_usage() {
-  printf "Usage: gen-ovpn -v [client name] -V [vpn server name] -p [protocol] -r [relay server] -a [user] -P [password] -e [destination email]
-  Port 587 will be used if a username AND password is provided to authenticate with the smtp relay, otherwise port 25 is used without authentication.
-  Non-authenticated smtp requests will likely be denied unless the IP it is being sent from is whitelisted.
+  printf "Usage: gen-ovpn -v [client name] -V [vpn server name] -p [protocol] -s [sender email] -e [destination email]
+
+  The mail command must be available for this script to work successfully and is expected to use an already configured
+  MTA that relays mail to a mail server that the relay is authorised to use.
 
   -v    Name given to the client .ovpn profile and associated certificates e.g. client1 (optional, lowers anonimity)
   -V    Friendly name of the VPN server e.g. PersonalVPN
   -p    Specify UDP or TCP for either UDP port 1194 or TCP port 443 for the VPN connection
-  -r    Name of the mail server that will act as the smtp relay to send the profile email
-  -a    Name used to authenticate with the smtp relay (optional)
-  -P    Password used to authenticate with the smtp relay (optional)
+  -s    Email address displayed as the sender of the profile email
   -e    The email address the .ovpn profile should be sent to
   -h    Prints these instructions
 "
 }
 
 # Flags
-while getopts 'v:V:p:r:d:a:P:e:h' flag; do
+while getopts 'v:V:p:s:e:h' flag; do
   case "${flag}" in
     v) vpnclient="${OPTARG}" ;;
     V) vpnname="${OPTARG}" ;;
     p) protocol="${OPTARG}" ;;
-    r) relaydomain="${OPTARG}" ;;
-    a) authuser="${OPTARG}" ;;
-    P) authpassword="${OPTARG}" ;;
+    s) senderemail="${OPTARG}" ;;
     e) destinationemail="${OPTARG}" ;;
     h) print_usage
        exit 0 ;;
@@ -54,9 +49,16 @@ while getopts 'v:V:p:r:d:a:P:e:h' flag; do
   esac
 done
 
+# Check that mail is available as a command
+if ! command -v mail &> /dev/null
+then
+    echo "The mail command could not be found. Please install the correct package for your operating system that contains mail"
+    exit 1
+fi
+
 # Check all required variables are present and protocol is correct
-if [[ -z "$vpnname" && -z "$protocol" && -z "$relaydomain" && -z "$destinationemail" ]]; then
-  echo -e "ERROR. A VPN name, protocol, relay domain and destination email address must be specified.\n"; echo ""
+if [[ -z "$vpnname" && -z "$protocol" && -z "$senderemail" && -z "$destinationemail" ]]; then
+  echo -e "ERROR. A VPN name, protocol, sender email address, and destination email address must be specified.\n"; echo ""
   exit 1
 elif ! [[ $protocol =~ ^(UDP|udp|TCP|tcp)$ ]]; then
   echo -e "ERROR. Please specify ether TCP or UDP protocol using -p\n"
@@ -94,23 +96,8 @@ fi
 } >>/etc/openvpn/client-profiles/"$vpnclient".ovpn
 
 # Send the .ovpn profile to the chosen email address
-if [[ -n "$authuser" && -n "$authpassword" ]]; then
-  sendemail \
-    -f "$vpnname <no-reply@$relaydomain>" \
-    -t "$destinationemail" \
-    -u "$vpnname OVPN Profile" \
-    -m "Hello,\n\nHere is your requested OVPN profile for "$vpnname".\n" \
-    -a /etc/openvpn/client-profiles/"$vpnclient".ovpn \
-    -s "$relaydomain":587 \
-    -o tls=auto \
-    -xu "$authuser" \
-    -xp "$authpassword"
-else
-  sendemail \
-    -f "$vpnname <no-reply@$relaydomain>" \
-    -t "$destinationemail" \
-    -u "$vpnname OVPN Profile" \
-    -m "Hello,\n\nHere is your requested OVPN profile for "$vpnname".\n" \
-    -a /etc/openvpn/client-profiles/"$vpnclient".ovpn \
-    -s "$relaydomain":25
-fi
+printf "Hello,\n\nHere is your requested OVPN profile for %s. \n" "$vpnname" | mail \
+  -s "$vpnname OVPN Profile" \
+  -a "FROM: ""$vpnname"" <""$senderemail"">" \
+  -A /etc/openvpn/client-profiles/"$vpnclient".ovpn \
+  "$destinationemail"
